### ISSUE TITLE
"Forgot Your Password" flow (basic UI; full implementation)

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gatekeeper#71]
- [x] Create a forget your password page with an email field (an email to send the forget your password link to).
   - [x] Only send the email if the UserAuth object with the email actually exists and that the email is valid (and lowercase)
   - [x] Make sure UserAuth is of type EmailAndPassword
- [x] Send an email with a link (and token similar to verify process) in which clicking on it lets the user enter a new password
   - [x] On submit, change the password (add a method in the UserAuthService for this)
- [x] Add a link to the login page above "Create an Account" that says "Forgot your password?"
This is a pretty big ticket, check the boxes to track your progress

**Comment by phulsechinmay** [comment]
Ah I do not want to write the tests for this
