### ISSUE TITLE
Setup Mailgun Service

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gatekeeper#8]
Create a service that lets someone sends emails to specific users. It should be able to take an email template filename as well as an object with the template files variables.

**Comment by phulsechinmay** [comment]
@geooot Mailgun has an internal API for storing and retrieving templates. Are we planning on using that for templating? This will change how templates are loaded & mail requests are sent to Mailgun.

**Comment by geooot** [comment]
@phulsechinmay I think any gatekeeper sent email should have templates and such controlled by the code. But we could probably use Mailguns template emails to send marketing emails and such.

**Comment by phulsechinmay** [comment]
@geooot So are we going to be using some sort of a filesystem where the template is stored? Just wondering how the MailService component will load the template and render the variables into it

**Comment by geooot** [comment]
@phulsechinmay Check out how Obos does their emails: https://github.com/tamuhack-org/Ouroboros/tree/master/hiss/templates/application/emails

They have template HTML files in a folder. The code just renders the templates as strings and sends the string to Mailgun. We could set up a similar thing using EJS or something
